repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.11
    hooks:
      # Sort imports.
      - id: ruff-check
        types_or: [python, pyi]
        args: ["--select", "I", "--fix"]
      # Run the linter.
      - id: ruff-check
        types_or: [python, pyi]
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
